<form data-mage-init='{"validation": {}, "Magento_Cms/js/widget": {}}'>
    <fieldset class="fieldset">
        <div class="field required">
            <label for="country_id" class="label">Enter country id</label>
            <div class="control">
                <input id="country_id" name="country_id" type="text" class="text-input" data-validate="{required: true}" placeholder="UA" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button class="action primary">Get country</button>
        </div>
    </div>
</form>
